name: CI - Selenium Maven

on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  testes:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verificar versão do Chrome
        run: chrome --version

      - name: Dar permissão ao Maven
        run: chmod +x mvnw

      - name: Executar os testes
        run: ./mvnw clean test